user_states = {}

STATES = {
    'WAITING_LOW_GENRE': 'WAITING_LOW_GENRE',
    'WAITING_HIGH_GENRE': 'WAITING_HIGH_GENRE',
    'WAITING_CUSTOM_GENRE': 'WAITING_CUSTOM_GENRE',
    'WAITING_CUSTOM_GENRE1': 'WAITING_CUSTOM_GENRE1',
    'WAITING_CUSTOM_GENRE2': 'WAITING_CUSTOM_GENRE2',
    'WAITING_CUSTOM_GENRE3': 'WAITING_CUSTOM_GENRE3',
}
